"""Project-local operating guide helpers."""

from __future__ import annotations

from pathlib import Path

AGENTS_MD_FILENAME = 'AGENTS.md'
MAX_OPERATING_GUIDE_CHARS = 8_000

LEGACY_DEFAULT_AGENTS_MD = """# Project Context

This file tracks the Databricks resources created in this project.
The AI assistant will update this file as resources are created.

## Configuration

- **Catalog:** (not yet configured)
- **Schema:** (not yet configured)

## Resources Created

### Tables
(none yet)

### Volumes
(none yet)

### Pipelines
(none yet)

### Jobs
(none yet)

## Notes

Add any project-specific notes or context here.
"""

DEFAULT_PROJECT_OPERATING_GUIDE = """# Project Operating Guide

This file describes reusable project-local rules for the Builder Agent and
Analysis Agent. It is not the project payload.

## Context Boundaries

- Treat project_setting.yaml and the injected Project Management Context as the
  source of truth for business background, analysis notes, Databricks resources,
  caveats, preferred tables, time windows, and group definitions.
- Use this file only for reusable operating rules: workflow, validation,
  evidence, persistence, escalation, and output conventions.
- Do not copy table IDs, resource inventories, one-off findings, SQL results, or
  conversation summaries into this file.

## Default Operating Rules

- Start data work with a concise visible plan and execute one started step at a
  time.
- Before analytical SQL, inspect the schema of configured tables or metric views
  and verify column names instead of inferring them from business language.
- Prefer project-configured Databricks resources. If a warehouse is not
  configured and a cluster is configured, use the cluster for SQL execution.
- Keep analysis-only chats read-oriented. Persist changes only when the user
  asks for an artifact, approves a durable rule, or the workflow creates a
  durable Databricks/app resource.
- In conclusions, separate measured results from assumptions, caveats, and
  recommended next steps.

## Updating This Guide

- Update this file only when the user asks to change how the agent should work
  for this project, or after explicitly confirming a reusable operating rule.
- Do not update this file for ordinary project_setting.yaml payload changes.
- Do not update this file after the final conclusion of a chat.
"""


def is_legacy_default_agents_md(content: str) -> bool:
  """Return true for the old resource-ledger placeholder AGENTS.md content."""
  return content.strip() == LEGACY_DEFAULT_AGENTS_MD.strip()


def is_meaningful_operating_guide(content: str) -> bool:
  """Return true when AGENTS.md has usable operating guidance."""
  stripped = content.strip()
  return bool(stripped) and not is_legacy_default_agents_md(stripped)


def ensure_project_operating_guide(project_dir: Path) -> tuple[Path, bool]:
  """Create or migrate the project operating guide.

  Existing user-authored AGENTS.md files are preserved. Only the exact legacy
  placeholder is replaced because it was generated by older app versions and
  contained no project-specific guidance.
  """
  project_dir.mkdir(parents=True, exist_ok=True)
  path = project_dir / AGENTS_MD_FILENAME
  if path.exists():
    try:
      existing = path.read_text(encoding='utf-8')
    except OSError:
      return path, False
    if not is_legacy_default_agents_md(existing):
      return path, False

  path.write_text(DEFAULT_PROJECT_OPERATING_GUIDE, encoding='utf-8')
  return path, True


def load_project_operating_guide(project_dir: Path) -> str:
  """Load a bounded start-of-run AGENTS.md snapshot for the system prompt."""
  path = project_dir / AGENTS_MD_FILENAME
  if not path.is_file():
    return ''
  try:
    content = path.read_text(encoding='utf-8')
  except OSError:
    return ''
  if not is_meaningful_operating_guide(content):
    return ''

  stripped = content.strip()
  if len(stripped) <= MAX_OPERATING_GUIDE_CHARS:
    return stripped
  return (
    stripped[:MAX_OPERATING_GUIDE_CHARS].rstrip()
    + '\n\n[AGENTS.md truncated to the first '
    + f'{MAX_OPERATING_GUIDE_CHARS} characters for this run.]'
  )
